cod1, qtde1, valor1 = input().split(" ")
cod2, qtde2, valor2 = input().split(" ")
total = (int(qtde1) * float(valor1)) + (int(qtde2) * float(valor2))
print(f'VALOR A PAGAR: R$ {total:.2f}')
print(end='')
